version: '3.9'

networks:
  desafio-network:

services:

  postgres:
    image: postgres:15
    container_name: desafio-postgres
    environment:
      POSTGRES_DB: gestao_atendimentos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - desafio-network

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: desafio-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@desafio.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - desafio-network

volumes:
  postgres-data:
